### ISSUE TITLE
Testida automaatset "deployd" githubis

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#59]
Eelduseks on, et Mihkel annab ligipääsu serverile...
ChatGPT abiga sain sellise näidiskoodi, mida tahaks proovida:
```
name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Change this to your desired Node.js version

    - name: Install project dependencies
      run: npm install

    - name: Deploy code to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -r --delete-after ./ user@your-server-ip:/path/to/remote/directory

    - name: Restart your Node.js app
      run: |
        ssh user@your-server-ip 'cd /path/to/remote/directory && npm install && pm2 restart your-app-name'
```
